<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Added a new link %link% to category "%category%".' => '',
    'Extend link validation by a connection test.' => '',
    'No description available.' => '',
    'The category you want to create your link in could not be found!' => '',
    'There have been no links or categories added to this space yet.' => '',
    'You can enable the extended validation of links for a space or user.' => '',
    'You miss the rights to add/edit links!' => '',
    'You miss the rights to delete this category!' => '',
    'You miss the rights to delete this link!' => '',
    'You miss the rights to edit this category!' => '',
    'You miss the rights to edit this link!' => '',
    'list' => '',
    '<strong>Confirm</strong> category deleting' => '<strong>Conferma</strong> cancellazione categorie',
    '<strong>Confirm</strong> link deleting' => '<strong>Conferma</strong> cancellazione link',
    'Cancel' => 'Annulla',
    'Delete' => 'Cancella',
    'Delete category' => 'Cancella categoria',
    'Delete link' => 'Cancella link',
    'Do you really want to delete this category? All connected links will be lost!' => 'Vuoi cancellare veramente questa categoria? Tutti i link legati verranno cancellati.',
    'Do you really want to delete this link?' => 'Vuoi veramente cancellare questo link?',
    'Link' => 'Link',
    'Linklist' => 'Lista Link',
    'Linklist Module Configuration' => 'Module Configurazione Lista Link',
    'Requested category could not be found.' => 'La categoria richiesta non può essere trovata.',
    'Requested link could not be found.' => 'Il link richiesto non può essere trovato.',
    'Save' => 'Salva',
    'Show the links as a widget on the right.' => 'Visualizza i link come widget sulla colonna di destra.',
];
