<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Added a new link %link% to category "%category%".' => '',
    'No description available.' => '',
    'list' => '',
    '<strong>Confirm</strong> category deleting' => '<strong>Confirmar</strong> borrado de la categoría',
    '<strong>Confirm</strong> link deleting' => '<strong>Confirmar</strong> borrado del enlace',
    'Cancel' => 'Cancelar',
    'Delete' => 'Borrar',
    'Delete category' => 'Borrar categoría',
    'Delete link' => 'Borrar enlace',
    'Do you really want to delete this category? All connected links will be lost!' => '¿Está seguro de que quiere borrar la categoría? Todos los enlaces serán eliminados',
    'Do you really want to delete this link?' => '¿Está seguro de que quiere borrar el enlace?',
    'Extend link validation by a connection test.' => 'Probar el enlace',
    'Link' => 'Enlace',
    'Linklist' => 'Lista de enlaces',
    'Linklist Module Configuration' => 'Configuración del módulo de enlaces',
    'Requested category could not be found.' => 'Categoría no encontrada',
    'Requested link could not be found.' => 'Enlace no encontrado',
    'Save' => 'Guardar',
    'Show the links as a widget on the right.' => 'Mostrar enlaces como bloque en la derecha',
    'The category you want to create your link in could not be found!' => '¡No se encuentra la categoría asociada al enlace!',
    'There have been no links or categories added to this space yet.' => 'Aún no existen enlaces o categorias en el espacio.',
    'You can enable the extended validation of links for a space or user.' => 'Puede activar la validación extendida de enlaces para un espacio o usuario.',
    'You miss the rights to add/edit links!' => '¡No tienes permisos para añadir/editar enlaces!',
    'You miss the rights to delete this category!' => '¡No tienes permisos para eliminar la categoría!',
    'You miss the rights to delete this link!' => '¡No tienes permisos para eliminar el enlace!',
    'You miss the rights to edit this category!' => '¡No tienes permisos para editar la categoría!',
    'You miss the rights to edit this link!' => '¡No tienes permisos para editar el enlace!',
];
