<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Category' => '',
    '<strong>Confirm</strong> category deleting' => '<strong>Confirmer</strong> la suppression de la catégorie',
    '<strong>Confirm</strong> link deleting' => '<strong>Confirmer</strong> la suppression du lien',
    'Added a new link %link% to category "%category%".' => 'Nouveau lien %link% ajouté à la catégorie "%category%".',
    'Cancel' => 'Annuler',
    'Delete' => 'Supprimer',
    'Delete category' => 'Supprimer la catégorie',
    'Delete link' => 'Supprimer le lien',
    'Do you really want to delete this category? All connected links will be lost!' => 'Voulez-vous vraiment supprimer cette catégorie ? Tous les liens attachés seront perdus !',
    'Do you really want to delete this link?' => 'Souhaitez-vous supprimer ce lien ?',
    'Extend link validation by a connection test.' => 'Etendre la validation du lien par un test de connexion.',
    'Link' => 'Lien',
    'Linklist' => 'Liste des liens',
    'Linklist Module Configuration' => 'Configuration du Module Linklist',
    'No description available.' => 'Pas de description disponible.',
    'Requested category could not be found.' => 'La catégorie demandée n\'a pu être trouvée.',
    'Requested link could not be found.' => 'Le lien demandé n\'a pu être trouvé.',
    'Save' => 'Enregistrer',
    'Show the links as a widget on the right.' => 'Montrer les liens dans un widget à droite de la page.',
    'The category you want to create your link in could not be found!' => 'La catégorie dans laquelle vous voulez créer votre lien n\'a pu être trouvée !',
    'There have been no links or categories added to this space yet.' => 'Il n\'y a encore aucun lien ou aucune catégorie dans cet espace.',
    'You can enable the extended validation of links for a space or user.' => 'Vous pouvez activer la validation étendue des liens pour un espace ou un utilisateur.',
    'You miss the rights to add/edit links!' => 'Vous n\'avez pas les droits pour ajouter/modifier des liens !',
    'You miss the rights to delete this category!' => 'Vous n\'avez pas les droits pour supprimer cette catégorie !',
    'You miss the rights to delete this link!' => 'Vous n\'avez pas les droits pour supprimer ce lien !',
    'You miss the rights to edit this category!' => 'Vous n\'avez pas les droits pour modifier cette catégorie !',
    'You miss the rights to edit this link!' => 'Vous n\'avez pas les droits pour modifier ce lien !',
    'list' => 'liste',
];
