<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Added a new link %link% to category "%category%".' => '',
    'No description available.' => '',
    'list' => '',
    '<strong>Confirm</strong> category deleting' => '<strong>Confirmar</strong> exclusão de categoria',
    '<strong>Confirm</strong> link deleting' => '<strong>Confirmar</strong> exclusão de link',
    'Cancel' => 'Cancelar',
    'Delete' => 'Excluir',
    'Delete category' => 'Excluir categoria',
    'Delete link' => 'Excluir link',
    'Do you really want to delete this category? All connected links will be lost!' => 'Você realmente quer apagar esta categoria? Todos os links relacionados serão perdidos!',
    'Do you really want to delete this link?' => 'Você realmente quer apagar este link?',
    'Extend link validation by a connection test.' => 'Estender validação de link por um teste de conexão.',
    'Link' => 'Link',
    'Linklist' => 'Links úteis',
    'Linklist Module Configuration' => 'Linklist Módulo de Configuração',
    'Requested category could not be found.' => 'Categoria solicitada não pôde ser encontrada.',
    'Requested link could not be found.' => 'Link solicitado não pôde ser encontrado.',
    'Save' => 'Salvar',
    'Show the links as a widget on the right.' => 'Mostrar os links como um widget na direita.',
    'The category you want to create your link in could not be found!' => 'A categoria que você deseja criar o seu link não foi encontrada!',
    'There have been no links or categories added to this space yet.' => 'Ainda não há links ou categorias adicionadas a este espaço.',
    'You can enable the extended validation of links for a space or user.' => 'Você pode ativar a validação estendida de links para um espaço ou usuário.',
    'You miss the rights to add/edit links!' => 'Você  não tem permissão para adicionar/editar links!',
    'You miss the rights to delete this category!' => 'Você não tem permissão para apagar esta categoria!',
    'You miss the rights to delete this link!' => 'Você  não tem permissão para eliminar este link!',
    'You miss the rights to edit this category!' => 'Você não tem permissão para editar esta categoria!',
    'You miss the rights to edit this link!' => 'Você não tem permissão para editar esse link!',
];
