<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Added a new link %link% to category "%category%".' => '',
    'No description available.' => '',
    'list' => '',
    'Back to modules' => 'Terug naar modules',
    'Could not determine content container!' => 'Kan inhoud container niet bepalen!',
    'Space not found!' => 'Ruimte niet gevonden!',
    'The item order was successfully changed.' => 'De volgore was succesvol aangepast.',
    'Toggle view mode' => 'Toggle weergavemodus',
    'You miss the rights to reorder categories.!' => 'Je hebt niet genoeg rechten om de volgorde van categorieën aan te passen!',
    '<strong>Confirm</strong> category deleting' => '<strong>Bevestig</strong> categorie verwijderen',
    '<strong>Confirm</strong> link deleting' => '<strong>Bevestig</strong> link verwijderen',
    'Cancel' => 'Annuleren',
    'Delete' => 'Verwijder',
    'Delete category' => 'Verwijderen categorie',
    'Delete link' => 'Verwijder link',
    'Do you really want to delete this category? All connected links will be lost!' => 'Ben je zeker dat je deze categorie wilt verwijderen? Alle verbonden links zullen verloren gaan!',
    'Do you really want to delete this link?' => 'Ben je zeker dat je deze link wilt verwijderen?',
    'Extend link validation by a connection test.' => 'Voer een connectietest uit bij het valideren van een link.',
    'Link' => 'Link',
    'Linklist' => 'Linklijst',
    'Linklist Module Configuration' => 'Linklijst Module COnfiguratie',
    'Requested category could not be found.' => 'Gevraagde categorie kon niet gevonden worden.',
    'Requested link could not be found.' => 'Gevraagde link kon niet gevonden worden.',
    'Save' => 'Bewaar',
    'Show the links as a widget on the right.' => 'Toon de links als een widget aan de rechterkant.',
    'The category you want to create your link in could not be found!' => 'De categorie waarin je je link wilt aanmaken kon niet gevonden worden!',
    'There have been no links or categories added to this space yet.' => 'Er zijn nog geen links of categorieën aan deze ruimte toegevoegd.',
    'You can enable the extended validation of links for a space or user.' => 'Je kan de uitgebreide validatie van links inschakelen voor een ruimte of een gebruiker.',
    'You miss the rights to add/edit links!' => 'Je hebt niet genoeg rechten om links toe te voegen of aan te passen!',
    'You miss the rights to delete this category!' => 'Je hebt niet genoeg rechten om deze categorie te verwijderen!',
    'You miss the rights to delete this link!' => 'Je hebt niet genoeg rechten om deze link te verwijderen!',
    'You miss the rights to edit this category!' => 'Je hebt niet genoeg rechten om deze categorie aan te passen!',
    'You miss the rights to edit this link!' => 'Je hebt niet genoeg rechten om deze link aan te passen!',
];
