<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Added a new link %link% to category "%category%".' => '',
    'No description available.' => '',
    'list' => '',
    '<strong>Confirm</strong> category deleting' => '<strong>Potvrzení</strong> smazání kategorie',
    '<strong>Confirm</strong> link deleting' => '<strong>Potvrzení</strong> smazání odkazu',
    'Cancel' => 'Zrušit',
    'Delete' => 'Smazat',
    'Delete category' => 'Smazat kategorii',
    'Delete link' => 'Smazat odkaz',
    'Do you really want to delete this category? All connected links will be lost!' => 'Opravdu chcete smazat tuto kategorii? Veškeré odkazy, které obsahuje, budou smazány!',
    'Do you really want to delete this link?' => 'Opravdu chcete smazat tento odkaz?',
    'Extend link validation by a connection test.' => 'Ověřit platnost odkazu pokusem o načtení stránky.',
    'Link' => 'Odkaz',
    'Linklist' => 'Odkazy',
    'Linklist Module Configuration' => 'Nastavení modulu Odkazy',
    'Requested category could not be found.' => 'Požadovaná kategorie nebyla nalezena.',
    'Requested link could not be found.' => 'Požadovaný odkaz nebyl nalezen.',
    'Save' => 'Uložit',
    'Show the links as a widget on the right.' => 'Zobrazit odkazy jako widget v pravém bočním menu.',
    'The category you want to create your link in could not be found!' => 'Kategorie, do které chcete přidat odkaz, nebyla nalezena.',
    'There have been no links or categories added to this space yet.' => 'Do tohoto prostoru nebyly přidány ještě žádné kategorie ani odkazy.',
    'You can enable the extended validation of links for a space or user.' => 'Zde můžete nastavit rozšířené možnosti ověření odkazu.',
    'You miss the rights to add/edit links!' => 'Nemáte oprávnění pro přidávání/upravování odkazů!',
    'You miss the rights to delete this category!' => 'Nemáte oprávnění pro smazání této kategorie!',
    'You miss the rights to delete this link!' => 'Nemáte oprávnění pro smazání tohoto odkazu!',
    'You miss the rights to edit this category!' => 'Nemáte oprávnění pro úpravu této kategorie!',
    'You miss the rights to edit this link!' => 'Nemáte oprávnění pro úpravu tohoto odkazu!',
];
