<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> category deleting' => '<strong>Löschen</strong> der Kategorie bestätigen',
    '<strong>Confirm</strong> link deleting' => '<strong>Löschen</strong> des Links bestätigen',
    'Added a new link %link% to category "%category%".' => 'Neuer Link %link% zur Kategorie "%category%" hinzugefügt.',
    'Cancel' => 'Abbrechen',
    'Delete' => 'Löschen',
    'Delete category' => 'Kategorie löschen',
    'Delete link' => 'Link löschen',
    'Do you really want to delete this category? All connected links will be lost!' => 'Möchtest du diese Kategorie wirklich löschen? Alle verknüpften Links gehen verloren.',
    'Do you really want to delete this link?' => 'Möchtest du diesen Link wirklich löschen?',
    'Extend link validation by a connection test.' => 'Erweiterte Linküberprüfung durch einen Verbindungstest.',
    'Link' => 'Link',
    'Linklist' => 'Linkliste',
    'Linklist Module Configuration' => 'Konfiguration Linklist Modul',
    'No description available.' => 'Keine Beschreibung verfügbar.',
    'Requested category could not be found.' => 'Die gewünschte Kategorie konnte nicht gefunden werden.',
    'Requested link could not be found.' => 'Der gewünschte Link konnte nicht gefunden werden.',
    'Save' => 'Speichern',
    'Show the links as a widget on the right.' => 'Zeige die Links als ein Widget am rechten Rand.',
    'The category you want to create your link in could not be found!' => 'Die Kategorie, in der du den Link erstellen möchtest, konnte nicht gefunden werden.',
    'There have been no links or categories added to this space yet.' => 'Zu diesem Space wurden noch keine Links oder Kategorien hinzugefügt.',
    'You can enable the extended validation of links for a space or user.' => 'Du kannst die erweiterte Überprüfung von Links für einen Space oder einen Benutzer aktivieren.',
    'You miss the rights to add/edit links!' => 'Du besitzt nicht die Berechtigung, um Links hinzuzufügen/zu bearbeiten!',
    'You miss the rights to delete this category!' => 'Du besitzt nicht die Berechtigung, um diese Kategorie zu löschen!',
    'You miss the rights to delete this link!' => 'Du besitzt nicht die Berechtigung, um diesen Link zu löschen!',
    'You miss the rights to edit this category!' => 'Du besitzt nicht die Berechtigung, um diese Kategorie zu bearbeiten!',
    'You miss the rights to edit this link!' => 'Du besitzt nicht die Berechtigung, um diesen Link zu bearbeiten!',
    'list' => 'Liste',
];
