<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Category' => '',
    '<strong>Confirm</strong> category deleting' => '<strong>تأیید</strong> حذف گروه',
    '<strong>Confirm</strong> link deleting' => '<strong>تأیید</strong> حذف پیوند',
    'Added a new link %link% to category "%category%".' => ' اضافه شد "%category%"به دسته بندي  %link%لينك  جديد',
    'Cancel' => 'انصراف',
    'Delete' => 'پاک کردن',
    'Delete category' => 'پاک کردن گروه',
    'Delete link' => 'پیوند را پاک کن',
    'Do you really want to delete this category? All connected links will be lost!' => 'آیا مطمئن هستید که می‌خواهید این گروه را پاک کنید؟ همه‌ی پیوندهای متصل پاک خواهند‌شد!',
    'Do you really want to delete this link?' => 'آیا مطمئن هستید که می‌خواهید این پیوند را پاک کنید؟',
    'Extend link validation by a connection test.' => 'اعتبار پیوند را با یک تست اتصال تمدید کنید.',
    'Link' => 'پیوند',
    'Linklist' => 'لیست پیوندی',
    'Linklist Module Configuration' => 'پیکربندی ماژول لیست پیوندی',
    'No description available.' => 'هيچي توضيحي موجود نيست',
    'Requested category could not be found.' => 'گروه درخواست‌شده یافت نشد.',
    'Requested link could not be found.' => 'پیوند درخواست‌شده یافت نشد.',
    'Save' => 'ذخیره',
    'Show the links as a widget on the right.' => 'پیوندها را به صورت ابزارک در سمت راست نمایش بده.',
    'The category you want to create your link in could not be found!' => 'گروهی که می‌خواهید پیوندتان را در آن بسازید یافت نشد! ',
    'There have been no links or categories added to this space yet.' => 'هنوز پیوند یا گروهی به این انجمن اضافه نشده‌است.',
    'You can enable the extended validation of links for a space or user.' => 'شما می‌توانید اعتبار تمدیدشده‌ی لینک‌ها را برای یک انجمن یا کاربر فعال کنید.',
    'You miss the rights to add/edit links!' => 'شما حق اضافه/ویرایش کردن پیوندها را ندارید!',
    'You miss the rights to delete this category!' => 'شما حق پاک کردن این گروه را ندارید!',
    'You miss the rights to delete this link!' => 'شما حق پاک کردن این پیوند را ندارید!',
    'You miss the rights to edit this category!' => 'شما حق ویرایش این گروه را ندارید!',
    'You miss the rights to edit this link!' => 'شما حق ویرایش این پیوند را ندارید!',
    'list' => 'ليست',
];
