<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Category' => '',
    '<strong>Confirm</strong> category deleting' => '<strong>Bekreft</strong> sletting av kategori',
    '<strong>Confirm</strong> link deleting' => '<strong>Bekreft</strong> sletting av link',
    'Added a new link %link% to category "%category%".' => 'La til en ny link %link% i kategori"%category%".',
    'Cancel' => 'Avbryt',
    'Delete' => 'Slett',
    'Delete category' => 'Slett kategori',
    'Delete link' => 'Slett link',
    'Do you really want to delete this category? All connected links will be lost!' => 'Ønsker du virkelig og slette denne kategorien? Alle linker vil forsvinne!',
    'Do you really want to delete this link?' => 'Ønsker du virkelig og slette denne linken?',
    'Extend link validation by a connection test.' => 'Forleng linkens gyldighet med en tilkoblings test.',
    'Link' => 'Link',
    'Linklist' => 'Link liste',
    'Linklist Module Configuration' => 'Link liste modul konfigurasjon ',
    'No description available.' => 'Ingen beskrivelse tilgjengelig.',
    'Requested category could not be found.' => 'Forespurt kategori ble ikke funnet.',
    'Requested link could not be found.' => 'Forespurt link ble ikke funnet.',
    'Save' => 'Lagre',
    'Show the links as a widget on the right.' => 'Vis Link listen som en widget på høyre side.',
    'The category you want to create your link in could not be found!' => 'Kategorien du ønsker og lagre linken i ble ikke funnet!',
    'There have been no links or categories added to this space yet.' => 'Det har ikke blitt lagt til noen linker og kategorier for denne gruppen enda.',
    'You can enable the extended validation of links for a space or user.' => 'Du kan aktivere link validering for en gruppe eller bruker.',
    'You miss the rights to add/edit links!' => 'Du mangler rettighetene til og redigere/legge til linker!',
    'You miss the rights to delete this category!' => 'Du mangler rettighetene til og slette denne kategorien!',
    'You miss the rights to delete this link!' => 'Du mangler rettighetene til og slette denne linken!',
    'You miss the rights to edit this category!' => 'Du mangler rettighetene til og redigere denne kategorien!',
    'You miss the rights to edit this link!' => 'Du mangler rettighetene til og redigere denne linken!',
    'list' => 'liste',
];
