<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> category deleting' => '',
    '<strong>Confirm</strong> link deleting' => '',
    'Add Category' => '',
    'Added a new link %link% to category "%category%".' => '',
    'Cancel' => '',
    'Delete' => '',
    'Delete category' => '',
    'Delete link' => '',
    'Do you really want to delete this category? All connected links will be lost!' => '',
    'Do you really want to delete this link?' => '',
    'Extend link validation by a connection test.' => '',
    'Link' => '',
    'Linklist' => '',
    'Linklist Module Configuration' => '',
    'No description available.' => '',
    'Requested category could not be found.' => '',
    'Requested link could not be found.' => '',
    'Show the links as a widget on the right.' => '',
    'The category you want to create your link in could not be found!' => '',
    'There have been no links or categories added to this space yet.' => '',
    'You can enable the extended validation of links for a space or user.' => '',
    'You miss the rights to add/edit links!' => '',
    'You miss the rights to delete this category!' => '',
    'You miss the rights to delete this link!' => '',
    'You miss the rights to edit this category!' => '',
    'You miss the rights to edit this link!' => '',
    'list' => '',
    'Save' => '儲存',
];
