<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Added a new link %link% to category "%category%".' => '',
    'No description available.' => '',
    'list' => '',
    '<strong>Confirm</strong> category deleting' => '<strong>Potwierdź</strong> usunięcie kategorii',
    '<strong>Confirm</strong> link deleting' => '<strong>Potwierdź</strong> usunięcie linku',
    'Cancel' => 'Anuluj ',
    'Delete' => 'Usuń ',
    'Delete category' => 'Usuń kategorię ',
    'Delete link' => 'Usuń link',
    'Do you really want to delete this category? All connected links will be lost!' => 'Czy naprawdę chcesz usunąć tę kategorię? Wszystkie powiązane linki zostaną usunięte. ',
    'Do you really want to delete this link?' => 'Czy naprawdę chcesz usunąć ten link?',
    'Extend link validation by a connection test.' => 'Rozszerz walidację linku przez test połączenia. ',
    'Link' => 'Link',
    'Linklist' => 'Lista linków',
    'Linklist Module Configuration' => 'Konfiguracja modułu Linklist',
    'Requested category could not be found.' => 'Nie można znaleźć żądanej kategorii. ',
    'Requested link could not be found.' => 'Nie można znaleźć żądanego linku. ',
    'Save' => 'Zapisz',
    'Show the links as a widget on the right.' => 'Po prawej stronie pokaż linki jako widget. ',
    'The category you want to create your link in could not be found!' => 'Nie można znaleźć kategorii do której chcesz utworzyć link! ',
    'There have been no links or categories added to this space yet.' => 'Do tej strefy nie ma jeszcze dodanych linków lub kategorii.',
    'You can enable the extended validation of links for a space or user.' => 'Możesz włączyć rozszerzoną walidację linków dla strefy lub użytkownika. ',
    'You miss the rights to add/edit links!' => 'Utraciłeś prawa do dodania lub edycji linków! ',
    'You miss the rights to delete this category!' => 'Utraciłeś prawa do usunięcia tej kategorii! ',
    'You miss the rights to delete this link!' => 'Utraciłeś prawa do usunięcia tego linku! ',
    'You miss the rights to edit this category!' => 'Utraciłeś prawa do edycji tej kategorii! ',
    'You miss the rights to edit this link!' => 'Utraciłeś prawa do edycji tego linku! ',
];
